# Generated by Django 3.2.23 on 2024-01-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('telepon', models.CharField(blank=True, max_length=20, null=True)),
                ('foto', models.ImageField(blank=True, upload_to='user')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, upload_to='anggota')),
                ('alamat', models.CharField(max_length=100)),
                ('telepon', models.CharField(max_length=20)),
                ('jabatan', models.CharField(max_length=100)),
                ('divisi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Divisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='KarangTaruna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, upload_to='karangtaruna')),
                ('foto_halaman_utama', models.ImageField(blank=True, upload_to='karangtaruna')),
                ('deskripsi_halaman_utama', models.TextField(blank=True, null=True)),
                ('lokasi', models.TextField(null=True)),
                ('alamat', models.CharField(max_length=100)),
                ('telepon', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=100)),
                ('foto_halaman_profil', models.ImageField(blank=True, upload_to='karangtaruna')),
                ('visi', models.TextField()),
                ('misi', models.TextField()),
                ('regulasi', models.TextField()),
                ('program_kerja', models.TextField()),
                ('motto', models.TextField()),
                ('deskripsi_halaman_profil', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Kependudukan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.TextField()),
                ('foto', models.ImageField(blank=True, upload_to='kependudukan')),
                ('jumlah_penduduk_total', models.IntegerField()),
                ('jumlah_penduduk_pria', models.IntegerField()),
                ('jumlah_penduduk_perempuan', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pengumuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('foto', models.ImageField(blank=True, upload_to='pengumuman')),
                ('lokasi', models.TextField(blank=True, null=True)),
                ('tanggal', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
