# Generated by Django 3.2.23 on 2024-01-23 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anggota',
            name='divisi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.divisi'),
        ),
    ]
