# Generated by Django 3.2.23 on 2024-01-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_anggota_divisi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pimpinan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='pimpinan')),
                ('telepon', models.CharField(max_length=20)),
                ('jabatan', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='anggota',
            name='foto',
            field=models.ImageField(upload_to='anggota'),
        ),
    ]
