# Generated by Django 3.2.15 on 2024-02-01 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_jumbotron'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jumbotron',
        ),
    ]
