# Generated by Django 3.2.15 on 2024-02-01 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_jumbotron'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karangtaruna',
            name='deskripsi_halaman_utama',
        ),
        migrations.RemoveField(
            model_name='karangtaruna',
            name='foto_halaman_utama',
        ),
    ]
