# Generated by Django 3.2.15 on 2024-02-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20240201_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karangtaruna',
            name='deskripsi_halaman_profil',
        ),
        migrations.RemoveField(
            model_name='karangtaruna',
            name='foto_halaman_profil',
        ),
        migrations.AlterField(
            model_name='jumbotron',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='jumbotron'),
        ),
        migrations.AlterField(
            model_name='karangtaruna',
            name='alamat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='karangtaruna',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='karangtaruna',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='karangtaruna',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='karangtaruna',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='karangtaruna'),
        ),
        migrations.AlterField(
            model_name='karangtaruna',
            name='lokasi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='karangtaruna',
            name='misi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='karangtaruna',
            name='motto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='karangtaruna',
            name='program_kerja',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='karangtaruna',
            name='regulasi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='karangtaruna',
            name='telepon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='karangtaruna',
            name='visi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
