# Generated by Django 3.2.15 on 2024-02-04 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_anggota_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anggota',
            options={'ordering': ['-jabatan']},
        ),
    ]
