# Generated by Django 3.2.15 on 2024-02-04 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_pimpinan_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pimpinan',
            options={'ordering': ['jabatan']},
        ),
    ]
